#%RAML 1.0 DataType
type: array
items:
  type: object
  properties:
    availableSeats:
      required: true
      type: number
      example: 20
    departureDateTime:
      required: true
      type: string 
      example: "2019-04-30T16:41:41.090Z"
    travelRoute:
      type: object
      properties:
        destinationLocation:
          type: object
          properties:
            locationCode:
              required: true
              type: string
              example:  "KLG-MY"
        originLocation:
          type: object
          properties:
            locationCode:
              required: true
              type: string
              example:  "BEN-SG"