#%RAML 1.0 Library
usage:
traits:
  transactionId:  !include /libraries/common/traits/header-transactionId-traits.raml
  departureLocationCode: !include /libraries/common/traits/queryParams-departureLocationCode-traits.raml
  destinationLocationCode: !include /libraries/common/traits/queryParams-destinationLocationCode-traits.raml
types:
  commonError: !include /libraries/common/dataTypes/common-error-dataType.raml